// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdminLoginRequest
 *
 * Request schema for admin login with email/password
 */
export type AdminLoginRequest = {
  /**
   * Email
   *
   * Admin email address
   */
  email: string;
  /**
   * Password
   *
   * Admin password
   */
  password: string;
};

/**
 * CardResponse
 *
 * Response schema for card details
 */
export type CardResponse = {
  /**
   * Id
   *
   * Card ID
   */
  id: string;
  /**
   * Owner Id
   *
   * Owner user ID
   */
  owner_id: string;
  /**
   * Idol
   *
   * Idol name
   */
  idol?: string | null;
  /**
   * Idol Group
   *
   * Idol group
   */
  idol_group?: string | null;
  /**
   * Album
   *
   * Album name
   */
  album?: string | null;
  /**
   * Version
   *
   * Version
   */
  version?: string | null;
  /**
   * Rarity
   *
   * Card rarity
   */
  rarity?: string | null;
  /**
   * Status
   *
   * Card status
   */
  status: string;
  /**
   * Image Url
   *
   * Image URL
   */
  image_url?: string | null;
  /**
   * Size Bytes
   *
   * Image size in bytes
   */
  size_bytes?: number | null;
  /**
   * Created At
   *
   * Creation timestamp
   */
  created_at: string;
  /**
   * Updated At
   *
   * Last update timestamp
   */
  updated_at: string;
};

/**
 * ErrorWrapper
 *
 * Error wrapper response
 */
export type ErrorWrapper = {
  /**
   * Data
   */
  data?: null;
  error: AppModulesIdentityPresentationSchemasProfileSchemasErrorResponse;
};

/**
 * GoogleCallbackRequest
 *
 * Request schema for Google OAuth callback with PKCE (Expo AuthSession)
 */
export type GoogleCallbackRequest = {
  /**
   * Code
   *
   * Authorization code from Google OAuth
   */
  code: string;
  /**
   * Code Verifier
   *
   * PKCE code verifier used during authorization request
   */
  code_verifier: string;
  /**
   * Redirect Uri
   *
   * Redirect URI used during authorization (must match the one used in auth request)
   */
  redirect_uri?: string | null;
};

/**
 * GoogleLoginRequest
 *
 * Request schema for Google login
 */
export type GoogleLoginRequest = {
  /**
   * Google Token
   *
   * Google ID token received from Google OAuth
   */
  google_token: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: ValidationError[];
};

/**
 * LoginResponse
 *
 * Response wrapper for successful login
 */
export type LoginResponse = {
  data: TokenResponse;
  /**
   * Error
   */
  error?: null;
};

/**
 * NearbyCardResponse
 *
 * Response schema for a nearby card result
 */
export type NearbyCardResponse = {
  /**
   * Card Id
   *
   * Card unique identifier
   */
  card_id: string;
  /**
   * Owner Id
   *
   * Card owner's user ID
   */
  owner_id: string;
  /**
   * Distance Km
   *
   * Distance from search origin in kilometers
   */
  distance_km: number;
  /**
   * Idol
   *
   * Idol name
   */
  idol?: string | null;
  /**
   * Idol Group
   *
   * Idol group name
   */
  idol_group?: string | null;
  /**
   * Album
   *
   * Album name
   */
  album?: string | null;
  /**
   * Version
   *
   * Card version
   */
  version?: string | null;
  /**
   * Rarity
   *
   * Card rarity
   */
  rarity?: string | null;
  /**
   * Image Url
   *
   * Card image URL
   */
  image_url?: string | null;
  /**
   * Owner Nickname
   *
   * Owner's nickname
   */
  owner_nickname?: string | null;
};

/**
 * ProfileErrorWrapper
 *
 * Error wrapper for profile endpoints
 */
export type ProfileErrorWrapper = {
  /**
   * Data
   */
  data?: null;
  error: AppModulesIdentityPresentationSchemasProfileSchemasErrorResponse;
};

/**
 * ProfileResponse
 *
 * Response schema for user profile
 */
export type ProfileResponse = {
  /**
   * Id
   *
   * Profile ID
   */
  id: string;
  /**
   * User Id
   *
   * User ID
   */
  user_id: string;
  /**
   * Nickname
   *
   * User nickname
   */
  nickname?: string | null;
  /**
   * Avatar Url
   *
   * Avatar image URL
   */
  avatar_url?: string | null;
  /**
   * Bio
   *
   * User bio/description
   */
  bio?: string | null;
  /**
   * Region
   *
   * User region
   */
  region?: string | null;
  /**
   * Preferences
   *
   * User preferences (JSON)
   */
  preferences?: {
    [key: string]: unknown;
  } | null;
  /**
   * Privacy Flags
   *
   * Privacy settings
   */
  privacy_flags?: {
    [key: string]: boolean;
  } | null;
  /**
   * Created At
   *
   * Profile creation timestamp
   */
  created_at: string;
  /**
   * Updated At
   *
   * Profile last update timestamp
   */
  updated_at: string;
};

/**
 * ProfileResponseWrapper
 *
 * Response wrapper for profile data
 */
export type ProfileResponseWrapper = {
  data: ProfileResponse;
  /**
   * Error
   */
  error?: null;
};

/**
 * QuotaStatusResponse
 *
 * Response schema for quota status
 */
export type QuotaStatusResponse = {
  /**
   * Uploads Today
   *
   * Number of uploads today
   */
  uploads_today: number;
  /**
   * Daily Limit
   *
   * Daily upload limit
   */
  daily_limit: number;
  /**
   * Remaining Uploads
   *
   * Remaining uploads for today
   */
  remaining_uploads: number;
  /**
   * Storage Used Bytes
   *
   * Total storage used in bytes
   */
  storage_used_bytes: number;
  /**
   * Storage Limit Bytes
   *
   * Storage limit in bytes
   */
  storage_limit_bytes: number;
  /**
   * Remaining Storage Bytes
   *
   * Remaining storage in bytes
   */
  remaining_storage_bytes: number;
  /**
   * Storage Used Mb
   *
   * Storage used in MB
   */
  storage_used_mb: number;
  /**
   * Storage Limit Mb
   *
   * Storage limit in MB
   */
  storage_limit_mb: number;
  /**
   * Remaining Storage Mb
   *
   * Remaining storage in MB
   */
  remaining_storage_mb: number;
};

/**
 * RefreshTokenRequest
 *
 * Request schema for refreshing access token
 */
export type RefreshTokenRequest = {
  /**
   * Refresh Token
   *
   * Refresh token
   */
  refresh_token: string;
};

/**
 * SearchNearbyRequest
 *
 * Request schema for nearby card search
 */
export type SearchNearbyRequest = {
  /**
   * Lat
   *
   * Latitude (-90 to 90)
   */
  lat: number;
  /**
   * Lng
   *
   * Longitude (-180 to 180)
   */
  lng: number;
  /**
   * Radius Km
   *
   * Search radius in kilometers (max 100km)
   */
  radius_km?: number | null;
};

/**
 * SearchNearbyResponse
 *
 * Response schema for nearby search results
 */
export type SearchNearbyResponse = {
  /**
   * Results
   *
   * List of nearby cards
   */
  results: NearbyCardResponse[];
  /**
   * Count
   *
   * Number of results returned
   */
  count: number;
};

/**
 * TokenResponse
 *
 * Response schema for authentication tokens
 */
export type TokenResponse = {
  /**
   * Access Token
   *
   * JWT access token
   */
  access_token: string;
  /**
   * Refresh Token
   *
   * JWT refresh token
   */
  refresh_token: string;
  /**
   * Token Type
   *
   * Token type
   */
  token_type?: string;
  /**
   * Expires In
   *
   * Access token expiration in seconds
   */
  expires_in: number;
  /**
   * User Id
   *
   * User ID
   */
  user_id: string;
  /**
   * Email
   *
   * User email
   */
  email: string;
  /**
   * Role
   *
   * User role (only for admin users)
   */
  role?: string | null;
};

/**
 * UpdateLocationRequest
 *
 * Request schema for updating user location
 */
export type UpdateLocationRequest = {
  /**
   * Lat
   *
   * Latitude (-90 to 90)
   */
  lat: number;
  /**
   * Lng
   *
   * Longitude (-180 to 180)
   */
  lng: number;
};

/**
 * UpdateProfileRequest
 *
 * Request schema for updating user profile
 */
export type UpdateProfileRequest = {
  /**
   * Nickname
   *
   * User nickname
   */
  nickname?: string | null;
  /**
   * Avatar Url
   *
   * Avatar image URL
   */
  avatar_url?: string | null;
  /**
   * Bio
   *
   * User bio/description
   */
  bio?: string | null;
  /**
   * Region
   *
   * User region
   */
  region?: string | null;
  /**
   * Preferences
   *
   * User preferences (JSON)
   */
  preferences?: {
    [key: string]: unknown;
  } | null;
  /**
   * Privacy Flags
   *
   * Privacy settings
   */
  privacy_flags?: {
    [key: string]: boolean;
  } | null;
};

/**
 * UploadCardRequest
 *
 * Request schema for getting upload signed URL
 */
export type UploadCardRequest = {
  /**
   * Content Type
   *
   * MIME type of the file (image/jpeg or image/png)
   */
  content_type: string;
  /**
   * File Size Bytes
   *
   * Size of file in bytes
   */
  file_size_bytes: number;
  /**
   * Idol
   *
   * Idol name
   */
  idol?: string | null;
  /**
   * Idol Group
   *
   * Idol group
   */
  idol_group?: string | null;
  /**
   * Album
   *
   * Album name
   */
  album?: string | null;
  /**
   * Version
   *
   * Version
   */
  version?: string | null;
  /**
   * Rarity
   *
   * Card rarity
   */
  rarity?: string | null;
};

/**
 * UploadUrlResponse
 *
 * Response schema for upload signed URL
 */
export type UploadUrlResponse = {
  /**
   * Upload Url
   *
   * Signed URL for uploading
   */
  upload_url: string;
  /**
   * Method
   *
   * HTTP method to use
   */
  method: string;
  /**
   * Required Headers
   *
   * Required headers for upload
   */
  required_headers: {
    [key: string]: string;
  };
  /**
   * Image Url
   *
   * Public URL of the image after upload
   */
  image_url: string;
  /**
   * Expires At
   *
   * When the signed URL expires
   */
  expires_at: string;
  /**
   * Card Id
   *
   * ID of the created card
   */
  card_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: (string | number)[];
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * ErrorResponse
 *
 * Error response schema
 */
export type AppModulesIdentityPresentationSchemasProfileSchemasErrorResponse = {
  /**
   * Code
   *
   * Error code
   */
  code: string;
  /**
   * Message
   *
   * Error message
   */
  message: string;
  /**
   * Details
   *
   * Additional error details
   */
  details?: {
    [key: string]: unknown;
  } | null;
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ApiHealthCheckApiV1HealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/health';
};

export type ApiHealthCheckApiV1HealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AdminLoginApiV1AuthAdminLoginPostData = {
  body: AdminLoginRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/admin-login';
};

export type AdminLoginApiV1AuthAdminLoginPostErrors = {
  /**
   * Validation error
   */
  400: ErrorWrapper;
  /**
   * Invalid credentials or not an admin
   */
  401: ErrorWrapper;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AdminLoginApiV1AuthAdminLoginPostError =
  AdminLoginApiV1AuthAdminLoginPostErrors[keyof AdminLoginApiV1AuthAdminLoginPostErrors];

export type AdminLoginApiV1AuthAdminLoginPostResponses = {
  /**
   * Successfully authenticated as admin
   */
  200: LoginResponse;
};

export type AdminLoginApiV1AuthAdminLoginPostResponse =
  AdminLoginApiV1AuthAdminLoginPostResponses[keyof AdminLoginApiV1AuthAdminLoginPostResponses];

export type GoogleLoginApiV1AuthGoogleLoginPostData = {
  body: GoogleLoginRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/google-login';
};

export type GoogleLoginApiV1AuthGoogleLoginPostErrors = {
  /**
   * Validation error
   */
  400: ErrorWrapper;
  /**
   * Invalid Google token
   */
  401: ErrorWrapper;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GoogleLoginApiV1AuthGoogleLoginPostError =
  GoogleLoginApiV1AuthGoogleLoginPostErrors[keyof GoogleLoginApiV1AuthGoogleLoginPostErrors];

export type GoogleLoginApiV1AuthGoogleLoginPostResponses = {
  /**
   * Successfully authenticated
   */
  200: LoginResponse;
};

export type GoogleLoginApiV1AuthGoogleLoginPostResponse =
  GoogleLoginApiV1AuthGoogleLoginPostResponses[keyof GoogleLoginApiV1AuthGoogleLoginPostResponses];

export type GoogleCallbackApiV1AuthGoogleCallbackPostData = {
  body: GoogleCallbackRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/google-callback';
};

export type GoogleCallbackApiV1AuthGoogleCallbackPostErrors = {
  /**
   * Validation error
   */
  400: ErrorWrapper;
  /**
   * Invalid authorization code or code_verifier
   */
  401: ErrorWrapper;
  /**
   * Token exchange failed
   */
  422: ErrorWrapper;
};

export type GoogleCallbackApiV1AuthGoogleCallbackPostError =
  GoogleCallbackApiV1AuthGoogleCallbackPostErrors[keyof GoogleCallbackApiV1AuthGoogleCallbackPostErrors];

export type GoogleCallbackApiV1AuthGoogleCallbackPostResponses = {
  /**
   * Successfully authenticated
   */
  200: LoginResponse;
};

export type GoogleCallbackApiV1AuthGoogleCallbackPostResponse =
  GoogleCallbackApiV1AuthGoogleCallbackPostResponses[keyof GoogleCallbackApiV1AuthGoogleCallbackPostResponses];

export type RefreshTokenApiV1AuthRefreshPostData = {
  body: RefreshTokenRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/refresh';
};

export type RefreshTokenApiV1AuthRefreshPostErrors = {
  /**
   * Invalid or expired refresh token
   */
  401: ErrorWrapper;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RefreshTokenApiV1AuthRefreshPostError =
  RefreshTokenApiV1AuthRefreshPostErrors[keyof RefreshTokenApiV1AuthRefreshPostErrors];

export type RefreshTokenApiV1AuthRefreshPostResponses = {
  /**
   * Successfully refreshed tokens
   */
  200: LoginResponse;
};

export type RefreshTokenApiV1AuthRefreshPostResponse =
  RefreshTokenApiV1AuthRefreshPostResponses[keyof RefreshTokenApiV1AuthRefreshPostResponses];

export type GetMyProfileApiV1ProfileMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/profile/me';
};

export type GetMyProfileApiV1ProfileMeGetErrors = {
  /**
   * Unauthorized
   */
  401: ProfileErrorWrapper;
  /**
   * Profile not found
   */
  404: ProfileErrorWrapper;
};

export type GetMyProfileApiV1ProfileMeGetError =
  GetMyProfileApiV1ProfileMeGetErrors[keyof GetMyProfileApiV1ProfileMeGetErrors];

export type GetMyProfileApiV1ProfileMeGetResponses = {
  /**
   * Successfully retrieved profile
   */
  200: ProfileResponseWrapper;
};

export type GetMyProfileApiV1ProfileMeGetResponse =
  GetMyProfileApiV1ProfileMeGetResponses[keyof GetMyProfileApiV1ProfileMeGetResponses];

export type UpdateMyProfileApiV1ProfileMePutData = {
  body: UpdateProfileRequest;
  path?: never;
  query?: never;
  url: '/api/v1/profile/me';
};

export type UpdateMyProfileApiV1ProfileMePutErrors = {
  /**
   * Validation error
   */
  400: ProfileErrorWrapper;
  /**
   * Unauthorized
   */
  401: ProfileErrorWrapper;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateMyProfileApiV1ProfileMePutError =
  UpdateMyProfileApiV1ProfileMePutErrors[keyof UpdateMyProfileApiV1ProfileMePutErrors];

export type UpdateMyProfileApiV1ProfileMePutResponses = {
  /**
   * Successfully updated profile
   */
  200: ProfileResponseWrapper;
};

export type UpdateMyProfileApiV1ProfileMePutResponse =
  UpdateMyProfileApiV1ProfileMePutResponses[keyof UpdateMyProfileApiV1ProfileMePutResponses];

export type GetUploadUrlApiV1CardsUploadUrlPostData = {
  body: UploadCardRequest;
  path?: never;
  query?: never;
  url: '/api/v1/cards/upload-url';
};

export type GetUploadUrlApiV1CardsUploadUrlPostErrors = {
  /**
   * Invalid request (file type/size)
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Quota exceeded
   */
  422: unknown;
};

export type GetUploadUrlApiV1CardsUploadUrlPostResponses = {
  /**
   * Upload URL generated successfully
   */
  200: UploadUrlResponse;
};

export type GetUploadUrlApiV1CardsUploadUrlPostResponse =
  GetUploadUrlApiV1CardsUploadUrlPostResponses[keyof GetUploadUrlApiV1CardsUploadUrlPostResponses];

export type GetMyCardsApiV1CardsMeGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status Filter
     *
     * Filter by status (available/trading/traded)
     */
    status_filter?: string | null;
  };
  url: '/api/v1/cards/me';
};

export type GetMyCardsApiV1CardsMeGetErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyCardsApiV1CardsMeGetError =
  GetMyCardsApiV1CardsMeGetErrors[keyof GetMyCardsApiV1CardsMeGetErrors];

export type GetMyCardsApiV1CardsMeGetResponses = {
  /**
   * Response Get My Cards Api V1 Cards Me Get
   *
   * Cards retrieved successfully
   */
  200: CardResponse[];
};

export type GetMyCardsApiV1CardsMeGetResponse =
  GetMyCardsApiV1CardsMeGetResponses[keyof GetMyCardsApiV1CardsMeGetResponses];

export type DeleteCardApiV1CardsCardIdDeleteData = {
  body?: never;
  path: {
    /**
     * Card Id
     */
    card_id: string;
  };
  query?: never;
  url: '/api/v1/cards/{card_id}';
};

export type DeleteCardApiV1CardsCardIdDeleteErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not the card owner
   */
  403: unknown;
  /**
   * Card not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCardApiV1CardsCardIdDeleteError =
  DeleteCardApiV1CardsCardIdDeleteErrors[keyof DeleteCardApiV1CardsCardIdDeleteErrors];

export type DeleteCardApiV1CardsCardIdDeleteResponses = {
  /**
   * Card deleted successfully
   */
  204: void;
};

export type DeleteCardApiV1CardsCardIdDeleteResponse =
  DeleteCardApiV1CardsCardIdDeleteResponses[keyof DeleteCardApiV1CardsCardIdDeleteResponses];

export type GetQuotaStatusApiV1CardsQuotaStatusGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/cards/quota/status';
};

export type GetQuotaStatusApiV1CardsQuotaStatusGetErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type GetQuotaStatusApiV1CardsQuotaStatusGetResponses = {
  /**
   * Quota status retrieved successfully
   */
  200: QuotaStatusResponse;
};

export type GetQuotaStatusApiV1CardsQuotaStatusGetResponse =
  GetQuotaStatusApiV1CardsQuotaStatusGetResponses[keyof GetQuotaStatusApiV1CardsQuotaStatusGetResponses];

export type SearchNearbyCardsApiV1NearbySearchPostData = {
  body: SearchNearbyRequest;
  path?: never;
  query?: never;
  url: '/api/v1/nearby/search';
};

export type SearchNearbyCardsApiV1NearbySearchPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Rate limit exceeded
   */
  429: unknown;
};

export type SearchNearbyCardsApiV1NearbySearchPostError =
  SearchNearbyCardsApiV1NearbySearchPostErrors[keyof SearchNearbyCardsApiV1NearbySearchPostErrors];

export type SearchNearbyCardsApiV1NearbySearchPostResponses = {
  /**
   * Search successful
   */
  200: SearchNearbyResponse;
};

export type SearchNearbyCardsApiV1NearbySearchPostResponse =
  SearchNearbyCardsApiV1NearbySearchPostResponses[keyof SearchNearbyCardsApiV1NearbySearchPostResponses];

export type UpdateUserLocationApiV1NearbyLocationPutData = {
  body: UpdateLocationRequest;
  path?: never;
  query?: never;
  url: '/api/v1/nearby/location';
};

export type UpdateUserLocationApiV1NearbyLocationPutErrors = {
  /**
   * Invalid coordinates
   */
  400: unknown;
  /**
   * User profile not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserLocationApiV1NearbyLocationPutError =
  UpdateUserLocationApiV1NearbyLocationPutErrors[keyof UpdateUserLocationApiV1NearbyLocationPutErrors];

export type UpdateUserLocationApiV1NearbyLocationPutResponses = {
  /**
   * Location updated successfully
   */
  204: void;
};

export type UpdateUserLocationApiV1NearbyLocationPutResponse =
  UpdateUserLocationApiV1NearbyLocationPutResponses[keyof UpdateUserLocationApiV1NearbyLocationPutResponses];
